[tools]
bat = "latest"
gh = "latest"
rg = "latest"
lazygit = "latest"
kustomize = "latest"
flux2 = "latest"
"github:control-theory/gonzo" = "latest"
"github:pehlicd/amtui" = "latest"
go = "latest"
"github:asciinema/asciinema" = "latest"
"github:asciinema/agg" = "latest"
"npm:tokscale" = "latest"
"npm:hunk" = "latest"
"npm:hunkdiff" = "latest"
git-cliff = "latest"
"pipx:graphifyy" = "latest"
"aqua:ouch-org/ouch" = "latest"
herdr = "latest"
dive = "latest"
fzf = "latest"
uv = "latest"
chezmoi = "latest"
