customCommands:
  - key: 'G'
    context: 'localBranches'
    command: "gh pr view --web || (echo 'Creating PR...' && gh pr create --web)"
    description: 'Open PR if it exists. Otherwise create a PR for this branch'
  - key: 'A'
    description: 'Add all, commit WIP, push'
    command: 'git add . && git commit -m "WIP" && git push'
    context: 'global'
gui:
  nerdFontsVersion: "3"
notARepository: 'skip'
