return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "black",
      "debugpy",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "hadolint",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "mdformat",
      "nginx-language-server",
      "pyright",
      "ruff-lsp",
      "shfmt",
      "stylua",
      "terraform-ls",
      "yaml-language-server",
      "bash-language-server",
      "shellcheck",
      "yamlfix",
    },
  },
}
