[username]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = false

[helm]
disabled = true

[directory]
style = "bold purple"

[git_branch]
style = "bold yellow"

[golang]
symbol = ""
disabled = true

[python]
disabled = true
